defaults: &defaults
  encoding: unicode
  adapter: postgresql
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *defaults
  database: blog_development

staging:
  <<: *defaults

test:
  <<: *defaults
  database: blog_test

production:
  <<: *defaults
  database: blog_test
